non_us_tickers = [
    "MC.PA", # LVMH
    "ITX.MC", # Inditex
    "CDI.PA", # Dior
    "KER.PA", # Kering
    "RMS.PA", # Hermès
    "CFR.SW", # Richemont
    "ADS.DE", # adidas
    "9983.T", # Fast Retailing
    "EL.PA", # Luxottica
    "HM-B.ST", # H&M
    "UHR.SW", # Swatch Group
    "ZAL.DE", # Zalando
    "1929.HK", # Chow Tai Fook
    "1913.HK", # Prada Group
    "BRBY.L", # Burberry
    "NXT.L", # Next
    "MONC.MI", # Moncler
    "ASC.L", # ASOS
    "LREN3.SA", # Lojas Renner
    "PUM.DE", # PUMA
    "MKS.L", # Marks & Spencer (M&S)
    "BOSS.DE", # Hugo Boss
    "GIL.TO", # Gildan
    "JD.L", # JD Sports
    "SFER.MI", # Salvatore Ferragamo
    "002563.SZ", # Semir
    "7936.T", # Asics
    "600612.SS", # Lao Feng Xiang Jewelry
    "BOO.L", # Boohoo.Com
    "FRAS.L", # Sports Direct -> Frasers Group
    "GRND3.SA", # Grendene
    "TOD.MI", # TOD'S
    "ALPA4.SA", # Alpargatas - Havaianas
    "BC.MI", # Brunello Cucinelli
    "2331.HK", # Li Ning
    "SDRY.L", # Supergroup -> Superdry
    "ABFRL.NS", # Aditya Birla Fashion and Retail
    "ARVIND.NS", # Arvind
    "8016.T", # Onward Holdings
    "7606.T", # United Arrows
    "002269.SZ", # Metersbonwe
    "SOMA3.SA", # Cia Hering -> Merged with Grupo Soma in 2021, now part of SOMA3.SA
    "3998.HK", # Bosideng
    "GEO.MI", # GEOX
    "0330.HK", # Esprit
    "MUL.L", # Mulberry
    "VAN.BR", # Van de Velde
    "GWI2.DE", # Gerry Weber
    "ATZ.TO", # Aritzia Inc.
    "WOSG.L", # Watches of Switzerland
    "MEKKO.HE", # Marimekko
    "AEF.MI", # Aeffe
    "BORG.ST", # Björn Borg
    "GFG.DE", # Global Fashion Group
    "SFL.MI", # Safilo Group
    "WOL.VI", # Wolford AG
    "YOU.DE", # ABOUT YOU
    "PPH.JO", # Pepkor
    "FOI-B.ST", # Fenix Outdoor
    "OVS.MI", # OVS S.p.A.
    "BOOZT.ST", # Boozt
    "3612.T", # World Co., Ltd.
    "4012.SR", # Thob Al Aseel Company
    "LINDEX.HE", # Lindex Group
    "DLTI.TA", # Delta Israel Brands
    "RVRC.ST", # RVRC Holding
    # "ILP.PK", # Interloop WERKT NIET
    "0709.HK", # Giordano
    "2368.HK", # Eagle Nice
    "SMCP.PA", # SMCP S.A.
    "MONTECARLO.NS", # Monte Carlo Fashions
    "DOLLAR.NS", # Dollar Industries
    "LUXIND.NS", # Lux Industries
    "LPP.WA", # LPP SA
    "MAVI.IS", # Mavi Giyim Sanayi ve Ticaret
    "6110.HK", # Topsports International
    "PMNT", # Perfect Moment
    "CALN.SW", # CALIDA Holding
    "ECK.DE", # LUDWIG BECK am Rathauseck
    "NXT.MC", # Nueva Expresión Textil
]

us_tickers = [
    "BCUCY", # Brunello Cucinelli
    "MYTE", # Mytheresa
    "BIRK", # Birkenstock
    "DBI", # DSW -> Designer Brands Inc. (DBI)
    "NKE", # Nike
    "TJX", # TJX
    "VFC", # VF
    "TPR", # Coach -> Tapestry
    "LULU", # Lululemon
    "CPRI", # Michael Kors -> Capri Holdings
    "M", # Macy's
    "RL", # Ralph Lauren
    "JWN", # Nordstrom
    "SKX", # Skechers
    "CRI", # Carter's
    "COLM", # Columbia Sportswear
    "FL", # Foot locker
    "DECK", # Deckers Outdoor
    "WWW", # Wolverine
    "LANV", # Lanvin Group (owns Wolford, Lanvin, St. John, Sergio Rossi, Caruso)
    "BURL", # Burlington Stores
    "ONON", # On Holding
    "LEVI", # Levi Strauss & Co.
    "CROX", # Crocs
    "KTB", # Kontoor Brands
    "VSCO", # Victoria's Secret
    "ZGN", # Ermenegildo Zegna
    "KSS", # KOHL'S
    "FIGS", # FIGS
    "GOOS", # Canada Goose
    "DOCS", # Dr. Martens
    "REAL", # The RealReal
    "ZUMZ", # Zumiez Inc
    "WEYS", # Weyco Group
    "TDUP", # ThredUp
    "RCKY", # Rocky Brands
    "BIRD", # Allbirds
    "RENT", # Rent the Runway
    "ROST", # Ross Stores
    "GPS", # Gap
    "GAP", # Gap Inc. (alternate ticker)
    "BBWI", # L Brands -> Bath & Body Works
    "PVH", # PVH HQ
    "VIPS", # Vipshop Holdings
    "HBI", # Hanes
    "UA", # Under Armour
    "URBN", # Urban Outfitters
    "AEO", # American Eagle Outfitters
    "DKS", # Dick's Sporting Goods
    "SHOO", # Steve Madden
    "PLCE", # Children's Place
    "DDS", # Dillard's
    "GIII", # G-III Apparel Group
    "ANF", # Abercrombie & Fitch
    "OXM", # Oxford Industries
    "GES", # GUESS
    "CAL", # Caleres
    "CHS", # Chico's
    "BKE", # Buckle
    "GCO", # Genesco
    "FOSL", # Fossil
    "EXPR", # Express
    "VRA", # Vera Bradley
    "CATO", # Cato Fashion
    "CTAS", # Cintas
    "BOOT", # Boot Barn Holdings
    "UNF", # UniFirst
    "RVLV", # Revolve
    "SVV", # Savers Value Village
    "CURV", # Torrid
    "JILL", # J.Jill
    "SGC", # Superior Group of Companies
    "MGOL", # MGO Global
    "LITB", # LightInTheBox Holding
]
